// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace courseapp.Models
{
    [Table("Course_Lesson")]
    public partial class CourseLesson
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Title { get; set; }
        [Column("Course_Id")]
        public int CourseId { get; set; }
        [Column("Order_Number")]
        public int? OrderNumber { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("CourseLesson")]
        public virtual Category Course { get; set; }
    }
}