// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace courseapp.Models
{
    public partial class Course
    {
        public Course()
        {
            TraineeCourses = new HashSet<TraineeCourses>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        [Column("Creation_Date", TypeName = "date")]
        public DateTime CreationDate { get; set; }
        public string Descriptoin { get; set; }
        [Column("Category_Id")]
        public int CategoryId { get; set; }
        [Column("Trainer_Id")]
        public int? TrainerId { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("Course")]
        public virtual Category Category { get; set; }
        [ForeignKey("TrainerId")]
        [InverseProperty("Course")]
        public virtual Trainer Trainer { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<TraineeCourses> TraineeCourses { get; set; }
    }
}