// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace courseapp.Models
{
    public partial class Trainer
    {
        public Trainer()
        {
            Course = new HashSet<Course>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        public string Description { get; set; }
        [StringLength(250)]
        public string Website { get; set; }
        [Column("Creation_Date", TypeName = "datetime")]
        public DateTime CreationDate { get; set; }

        [InverseProperty("Trainer")]
        public virtual ICollection<Course> Course { get; set; }
    }
}