// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace courseapp.Models
{
    [Table("Trainee_Courses")]
    public partial class TraineeCourses
    {
        [Key]
        [Column("Trainee_Id")]
        public int TraineeId { get; set; }
        [Key]
        [Column("Course_Id")]
        public int CourseId { get; set; }
        [Column("Registration_date", TypeName = "datetime")]
        public DateTime RegistrationDate { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("TraineeCourses")]
        public virtual Course Course { get; set; }
        [ForeignKey("TraineeId")]
        [InverseProperty("TraineeCourses")]
        public virtual Trainee Trainee { get; set; }
    }
}